services:
  frontend:
    build:
      context: ./frontend
    container_name: todo-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run host-dev
  backend:
    build:
      context: ./backend-node
    container_name: todo-backend
    ports:
      - "3030:3030"
    volumes:
      - ./database:/database
